= GitHub pushed
:stem:
:Bs: \mathcal{B}
:Gs: \mathcal{G}
:Cs: \mathcal{C}
:Ks: \mathcal{K}
:N: \mathbb{N}

== Doc
$ xdotool search --name "Mozilla Firefox"
$ xdotool search --name "emacs"
$ while inotifywait -e close_write GitHub\ pushed.adoc; do asciidoctor GitHub\ pushed.adoc; xdotool windowactivate 27263037; xdotool key CTRL+r; xdotool windowactivate 69206338; done

== Restriction
The analysis below covers the case of a commit on which some branch was created or updated. A commit may also have a “null” push date, in which case its creation instant is the earliest creation instant (in the sense of this analysis) among its children.

== Defs
- Small greek letters designate instants; capital greek letters designate sets of instants.
- Capital latin letters designate commits
- Calligraphic latin letters designate sets of references or commits
- Small latin letters designate functions

“Instant” means timestamp (date and time, Instant in Java).
Let \(ν\) designate “now” and \(Σ = ]−∞, ν[ \) be the set of possible past event instants. Because of the limited precision of “instants”, two events that are in reality consecutive may be considered here to have happened at the same “instant”.
The letter \(τ\) designate real event instants, thus with \(τ \in Σ\), while \(σ\) designate instants as known by us (that is, given by GitHub or unknown), with \(σ \in [−∞, ν]\) unless specified otherwise.

- \({Cs}\) the commits in the GitHub repository
- Commit \(X \in {Cs}\) the one we are interested in.
- \( {Bs} \) the set of refs (branches) that the GitHub repo ever had (thus not containing local branchs that never reached the GitHub repo)
- Given \(B \in \mathcal{B}\):
** \(u^B \in {N} \) the number of updates of branch \(B\), \(0\) iff the branch was created and never updated;
** \( τ^B_i, i \in [0, u^B] \), the \(i\)th update instant of branch \(B\), with \( \forall i \in [0, u^B - 1]: τ^B_i ≤ τ^B_{i + 1} \)
** thus with \( τ^B_0 \) the create instant of branch \(B\),
** \( c^B: [0, u^B] → {Cs} \), \( c^B(i) \) designates the commit that \(B\) was at during \(i\)th update;
- \( {Gs} \subseteq {Bs} \) the branches known by GitHub (with \( {Gs} ≠ {Bs} \) iff a branch has been deleted sufficiently long ago)
- Given \(B \in {Gs}\):
** \(σ^B_0\) the branch creation instant reported by GitHub, or \(−∞\) if unknown;
** \(ũ^B \in {N}\) the number of PushEvents reported by GitHub concerning branch \(B\)
** \( σ^B_i, i \in [1, ũ^B] \) the \(i\)th PushEvent reported by GitHub, ordered by instant (\(σ^B_i ≤ σ^B_{i + 1} \))
** \( ĉ^B: [0, ũ^B] → {Cs} \) the commit that the branch reportedly was at during the CreateEvent or \(i\)th PushEvent;
- \( τ^R = \min_{B \in {Bs}} τ^B_0 \) the repository creation instant
- \(σ^R \in Σ \) the repository creation instant reported by GitHub
- \(τ^X_L\) any lower bound on the existence of \(X\) (−∞ is suitable, or any instant before the challenge was given, for example)
- \( {Ks} = \{C \in {Cs} \mid \exists B, i \mid c^B(i) = C\} \) the commits on which some branch was ever created or updated.

Given \(C \in {Cs} \):

- \(σ^C_P\) the pushed instant reported by GitHub
- latexmath:[ τ^C_0 = \min \{τ^B_i \mid c^B(i) = C\} ] the creation instant of \(C\), assuming that \( C \in {Ks} \)

== Hypothesis about the data reported by GitHub
- \( ũ^B ≤ u^B \)
- latexmath:[ \forall 0 ≤ k ≤ ũ^B: σ^B_{ũ^B - k} = τ^B_{u^B - k} ]
- latexmath:[ σ^C_P = \max \{τ^B_i \mid c^B(i) = C\} ]
- \( σ^R = \min_B τ^B_0 \)
- The sigmas are upwards closed: \( \exists B, i, B', i' \mid σ^B_i ≤ τ^{B'}_{i'} ⇒ \exists j \mid σ^{B'}_j = τ^{B'}_{i'} \)

== Claims
(Not sure that they are useful.)

- \( \min_{B \in {Gs}} σ^B_0 = σ^R ⇒ {Gs} = {Bs} \land \forall B \in {Bs}: σ^B_0 = τ^B_0. \)
- \( τ^R ≤ \min_B τ^B_0 \).

== Theorem
If our knowledge reaches before the creation of \(C\) (that is, reaches \(σ^R\) or goes back to \(τ^C_L\) or before), then we know the creation time of \(C\).

latexmath:[ {Gs} ≠ \emptyset \land \min_{B \in {Gs}} σ^B_0 ≤ \max \{σ^R, τ^C_L\} ⇒ τ^C_0 = \min \{σ^B_i \mid ĉ^B(i) = C\} ].

== Negative result
If repo created at time α and we know history since time β and the min pushed time among the children of X is γ, with α ≤ β ≤ γ, then X could have been created anywhere in ]α, β[ or at γ. Any time in [α, β[ is feasible, whatever the observed history: for example, the whole repo could have existed just after α then history re-written according to observed history by moving refs?
